## Vagrant's Descent

A deep dark hole.
And he is falling through it.
He has nothing, just his loose, long-worn garments.
So deep, he can't see the top if he rolls over.
He can't see the ground either, not even the walls, it must be wide.
Why was he thrown down here?
The vagrant is not sure.
He has been a bearer for the curse for such a long time, maybe it was something he forgot.
How long has he been falling?
He can't tell either, but it feels like it has been hours at least.
Maybe days.
Darkness makes one lose track of time.

What is he going to do?
There is nothing, he knows that all he can do is just fall and hope to reach the ground.
He cares not if he survives the fall, he just wants it to be over.
But there is nary a thing that could tell him when the end is coming.
Just like a prisoner on a death row.

When one is subject to too much light, they don't see anything and their mind is dull.
But in the darkness, the mind is racing, thoughts bubbling up one over another.
The mind looks at the darkness as an empty canvas, ready to be painted. |

<small>| Wow, this is an actual scientific fact! Sort of, at least... Either way, one starts hallucinating when subjected to too much darkness.</small>

There is nothing we can do about it.
And the vagrant starts seeing things.

Visions of walls, but when he tries to reach them, they disappear and his hand goes through, still in the darkness.
His mind is still clinging to the thought that it can measure the hole and figure out when it's all going to end.
He needs to delve deeper.
Grim thoughts start crossing his mind.
Is he still in this world?
Is this perhaps a dream or maybe this is what comes after death?
No, that's not it.
The curse is still strong and he can still feel it burning in his chest.
What has he done to deserve this?
He can't remember.
Not sure who he was, or what he lived for.

In the darkness, he starts seeing shapes.
It's his home.
He can see his siblings and his parents.
Where did they end up?
His parents are dead.
He is glad they are.
He wouldn't wish the curse of dying a thousand times and not really dying upon them.
The siblings, though, they were too young, maybe some of them share his fate.
They haven't spoken in years, not since he was killed and came back.
The vagrant feels sad, but he can't do anything about it.
Long ago, his homeland fell and crumbled and a new empire is being built in its place.
He is not sure if any of his siblings are even still alive.
But at least now he knows who he was.

The hole doesn't end, but he is content with it.
The vagrant knows that eventually, he will reach the bottom.
It is either the end or the beginning.
No one can tell yet, but all will be revealed.
But he is no longer nervous about when it will be.
Perhaps he doesn't have anything he would live for anymore...

Sadness fills his heart.
Suddenly, he sees her in the darkness.
The one he loved.
A jolly, kind girl.
She was always so nice to him.
He struggled to tell her how much he loved her, but he couldn't.
The words were in his mind, but they never reached the tongue.
He was afraid he would hurt her, or that she wouldn't share his feelings.
Now he will never know.
He was so sad when she left...
He never saw her again.
The vagrant hopes she is still alive somewhere, but deep down, he fears.
How would such a sweet, kind flower withstand the agony of the curse?


There are things that we can affect and there are things we cannot.
Which ones make us sadder?
Sometimes we don't even know if we had the power to change the outcome, but when we do, it hurts a thousand times more.
It is the pain of responsibility.
And the regret lingers.

How many of those did the vagrant have?
To become one, you surely need many.
And he keeps falling.
Whichever of his choices led to this outcome?
He still doesn't know.
But he starts to feel.
It is getting warmer.
He is glad because he has been falling through the cold for so long.
He can at least try to stretch his joints now.

The vagrant sees once again.
This time, it is the day he left the family.
He had an argument with his father.
His memory is a bit foggy, but he knows why it was.
It is because he lost his dad's ax.
A new piece of equipment and it cost a weeks worth of pay.
He knows he was angry, he yelled at him.
There was no particular reason, it was just to answer the yells of his father.
Oh, how he wishes he could take back the things he said.
The anger has clouded his judgment. Maybe there is a hint of shame.
But it can't be taken back.
Things are gone, and they will never return.
He now knows the adverse effects of clinging to material things.
He wishes his father had known that as well.

The vagrant feels it getting warmer.
He is quite comfortable now.
Nary a thing in sight, but he doesn't mind that at all.
He tries to whistle, only to see if there is an echo, but it never comes.
No matter, there are more, more troubling things to worry about.
The vagrant found certainty in his uncertain state.
But not within himself.

In the distance, he sees himself, still young.
Alone, he has left his family a long time ago.
His parents aren't alive anymore.
He remembers the spark of sadness that lit in him at that moment.
But it was quickly gone, he was focusing on the road.
The vagrant sees two wights approaching slowly through the foliage.
He remembers now.
They are getting closer.
He wants to warn himself so much, but he can't.
It has already happened, it is just a vision.
One of the brigands throws a stone and leaves the foliage.
The vagrant turns around, but it was a mistake.
It's what they wanted.
Another one catches him from behind and puts a knife to his throat.
They want his money, but he can't give any, he has nothing.
Not a smithereen.
He tries to explain, but the robbers are jittery.
Oh no, they don't want to listen.
And he can feel the knife slashing his throat.

The brigands run away.
He is holding his throat, not sure what to do.
A few stumbles, but strength is leaving him too fast.
The legs give up and he falls to the ground.
His arms are too weak, too, he can't hold his throat.
What is he going to do?
He panics for a moment.
But there is nothing to be done.
You can't heal a slashed throat by yourself.

It's getting darker, and colder.
But he has come to terms with his condition.
In a few moments, he will be freed from this mortal coil.
There is peace.
Darkness will shortly settle and his eyes can't stay open anymore.
He gives in to the sweet embrace of this harsh mistress.

But he is rejected.
The vagrant sees nothing, feels nothing.
Nothing but fire, burning inside him.
Burning his flesh and bones.
Flowing through his entire body.
And he hears it.
Resonating through the flame.
A thousand screams.
It is not sensible, just screams.
Thousands of those who are lost working together to bring this poor vagrant back.
A unison of dark voices.
No one should be brought back alone.
They start singing.
A song of light and darkness.
Of the Flame and the Dark.
They are caught here, accursed, just like him.
They can never leave, but he can.
He can go to try and make a difference.
To try and break the curse.
He is not sure if he can, or if he even understands.
But he feels it, the pain of thousands undead who have hollowed so much they can't move and their bones burn brightly in a bonfire.
They have only suffering left, but not he.
The vagrant is still free from this pain, but not from the curse that causes it.
Now it is the darkness that burns brightly in him.
The essence of man.

The vagrant feels himself as but an idea.
And the idea is being encased in bones, once again.
The flame chews and spits back, only eating a little every time.
Strings of flesh are pulled onto the bones.
The flesh thickens and skin spreads over the carcass to cover it.
Just the bits now, his face, his hair and finally, his garments.

The vagrant is brought back, spat out by a bonfire.
He is gasping, desperately trying to catch his breath.
The memory is still fresh and the feeling is strong.
He won't feel it again.
And the voices won't be heard again.
The vagrant will die a thousand deaths afflicted by the curse...

He snaps back to reality.
It is quite hot now.
Almost burning.
The vagrant starts seeing dim, red light.
The light grows stronger.
And so does the heat.
He is still wondering where is he falling into or what is the source of the light.
Sweat would run down his face if it wasn't for the upwards wind blowing it off his face.
The light grows stronger.
And now he sees around himself much better.
He can see the walls, they are so far away.
It's wood.
He realizes now, he is falling down an archtree.
One, that was buried long ago, a tree that survived the test of time.
It may have been dead for a long time, but it will take so long before the tree molders completely.

He remembers.
Oh yes, that's why he is falling down the tree.
Desperate, he jumped down himself, down the trunk of a great, dead tree.
It was a weak moment.
A call of the void they call it.
He didn't know what would await down there.
But now, he sees it.
Deep down, a field of flames.
Blazes, here and there.
There are cinders around, the flame must have used to burn much brighter.
Ah, it is all clear now.
This old archtree, a remnant of the Age of Dragons, a world with immortal dragons and gray crags, is the host to the Primordial Flame, the originator of disparity.

But the vagrant isn't here to become cinders.
He isn't going to be a sacrifice to the flames, cause of so much pain.
No, he now remembers the screams of those he saw within the flames of the bonfire.
Their suffering and their hopes.
He is desperate.
Not just desperate, the feeling of desperation fills every inch of his body.
And that's just enough to light a spark.

The vagrant is falling into a flaming kiln.
The heat is so great that his cape is starting to catch fire and little flames dance on his garments.
But the desperation makes a spark.
An unholy forbidden marriage of the essence of a flame and the darkness of man.
The forbidden black flame.
Yes, he bursts into flames, those with tiny white roots and blazing black tips.
Determined to fight fire with fire.

A faraway observer would see a field of fire slowly coming into contact with a majestic black corona.
They would not hear the noise of both fires.
Such a distant person perceives all of this in silence.
A silent clash of the Flame and the Dark.

The vagrant is burning strong with black flame.
Preparing for a landing into the field of fire.
He isn't here to become cinders.
Burning bright, two monsters, belike two eyes that gaze upon one another.
The vagrant takes a dive.

An explosion.
The yellow flames are quickly overpowered, suffocated by the forbidden black flame.
Power runs through the body of the vagrant who stands amidst it all.
But alas, he can't defeat the flame completely today.
The Primordial Flame has roots deep and it still strong.
But it is defeated and it does it's best to retreat.
It's but a smoldering field now.
And a strong, black flame in the middle.

The vagrant channels the power of the black flame, let's it flow through his cursed bones.
With a mighty stomp, he hits the Primordial time for the last time and propels himself from the ground.
Powered by the forbidden force, he quickly ascends through the stump.
A rumbling can be heard deep underground, almost as if a volcano was about to erupt.
And when the vagrant finally gets enough the ground, it certainly looks like it.
An old wooden stump spitting out a mass of black flames.
The vagrant flies high off the ground and slowly lands.
He is now back up and he knows, who he is and what he lives for.

By the power of the forbidden flame, the undead vagrant becomes unkindled, unable to catch fire.
He is unkindled ash and he will kill the flame once and for all.
Risen from his dark and spacious grave to free mankind from the disparity.
